services:
  mongodb:
    image: mongo:7.0
    restart: always
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INIT_DB}
  mariadb:
    image: mariadb:10.5
    restart: always
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mariadb-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=${MARIA_DB_NAME}
      - MYSQL_USER=${MARIA_USER}
      - MYSQL_PASSWORD=${MARIA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIA_ROOT_PASSWORD}
  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - redis-network
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
  jaeger:
    image: jaegertracing/all-in-one:1.57
    restart: always
    ports:
      - "4317:4317"
      - "16686:16686"

volumes:
  mongodb-data:
  mariadb-data:
  redis-data:
  
networks:
  redis-network:
    driver: bridge